FROM python:3.8-slim

RUN apt-get update && apt-get install -y git gcc libpcre3-dev poppler-utils tesseract-ocr tesseract-ocr-spa tesseract-ocr-cat antiword
RUN pip install pip==24.0

COPY requirements.txt requirements-dev.txt /tmp/
RUN pip install -r /tmp/requirements.txt
RUN pip install -r /tmp/requirements-dev.txt

WORKDIR /app
